//不稳定红石余烬
stoneCutter.addRecipe("unstable_redstone_part.combatant", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/combatant"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.samurai", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/samurai"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.warlord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/warlord"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.ballast", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/ballast"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.magnum", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.brawlers", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/brawlers"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.guardian", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/guardian"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/lightning"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.lunar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/lunar"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.solar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/solar"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.slipstream", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/slipstream"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.splendor", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/splendor"}), <item:yuusha:unstable_redstone_part>);
stoneCutter.addRecipe("unstable_redstone_part.tyrannical", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/tyrannical"}), <item:yuusha:unstable_redstone_part>);

//玄奥沙 升级  
craftingTable.addShaped("uncommon_to_epic_material.combatant", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/combatant"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/combatant"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.samurai", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/samurai"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/samurai"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.warlord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/warlord"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/warlord"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.ballast", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/ballast"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/ballast"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.magnum", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.brawlers", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/brawlers"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/brawlers"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.guardian", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/guardian"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/guardian"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lightning"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/lightning"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.lunar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lunar"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/lunar"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.solar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/solar"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/solar"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.slipstream", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/slipstream"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/slipstream"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.splendor", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/splendor"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/splendor"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.tyrannical", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/tyrannical"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:core/tyrannical"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.earth", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:overworld/earth"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:overworld/earth"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("uncommon_to_epic_material.royalty", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:overworld/royalty"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:overworld/royalty"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);

//玄奥沙 升级  
craftingTable.addShaped("rare_to_epic_material.combatant", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/combatant"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/combatant"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.samurai", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/samurai"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/samurai"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.warlord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/warlord"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/warlord"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.ballast", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/ballast"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/ballast"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.magnum", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.brawlers", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/brawlers"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/brawlers"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.guardian", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/guardian"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/guardian"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lightning"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/lightning"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.lunar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lunar"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/lunar"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.solar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/solar"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/solar"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.slipstream", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/slipstream"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/slipstream"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.splendor", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/splendor"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/splendor"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.tyrannical", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/tyrannical"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:core/tyrannical"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.blood_lord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_nether/blood_lord"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:the_nether/blood_lord"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("rare_to_epic_material.inferno", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_nether/inferno"}), [[<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>], [<item:apotheosis:epic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:the_nether/inferno"}), <item:apotheosis:epic_material>], [<item:minecraft:air>, <item:apotheosis:epic_material>, <item:minecraft:air>]]);

//神铸珍珠 升级  
craftingTable.addShaped("epic_to_mythic_material.combatant", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/combatant"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/combatant"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.samurai", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/samurai"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/samurai"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.warlord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/warlord"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/warlord"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.ballast", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/ballast"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/ballast"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.magnum", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis_modern_ragnarok:core/amr/magnum"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.brawlers", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/brawlers"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/brawlers"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.guardian", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/guardian"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/guardian"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/lightning"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lightning"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.lunar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/lunar"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/lunar"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.solar", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/solar"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/solar"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.slipstream", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/slipstream"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/slipstream"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.splendor", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/splendor"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/splendor"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.tyrannical", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/tyrannical"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/tyrannical"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.blood_lord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:the_nether/blood_lord"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_nether/blood_lord"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.inferno", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:the_nether/inferno"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_nether/inferno"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.earth", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:overworld/earth"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:overworld/earth"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.royalty", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:overworld/royalty"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:overworld/royalty"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.endersurge", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:the_end/endersurge"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_end/endersurge"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.mageslayer", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:the_end/mageslayer"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_end/mageslayer"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("epic_to_mythic_material.breach", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "apotheosis:core/breach"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/breach"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);

//吟唱缩减 复制
craftingTable.addShapeless("irons_spellbooks.cast_time.copy", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cast_time"}) * 2, [<item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cast_time"}), <item:yuusha:burn_core>]);

//神铸珍珠 升级法术宝石
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.cooldown", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:cooldown"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cooldown"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.blood", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:blood"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:blood"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.cast_time", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:cast_time"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cast_time"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.ender", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:ender"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:ender"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.evocation", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:evocation"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:evocation"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.fire", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:fire"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:fire"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.holy", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:holy"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:holy"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.ice", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:ice"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:ice"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.intelligent", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:intelligent"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:intelligent"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:lightning"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:lightning"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.nature", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:nature"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:nature"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.spell_resist", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:spell_resist"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:spell_resist"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);
craftingTable.addShaped("irons_spellbooks.epic_to_mythic_material.summoning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:mythic"}, gem: "irons_spellbooks:summoning"}), [[<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>], [<item:apotheosis:mythic_material>, <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:summoning"}), <item:apotheosis:mythic_material>], [<item:minecraft:air>, <item:apotheosis:mythic_material>, <item:minecraft:air>]]);

//玄奥沙制作 法术宝石
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.cooldown", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cooldown"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:cooldown_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.blood", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:blood"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:blood_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.cast_time", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:cast_time"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:blank_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.ender", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:ender"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:ender_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.evocation", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:evocation"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>,<item:irons_spellbooks:evocation_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.fire", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:fire"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:fire_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.holy", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:holy"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:holy_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.ice", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:ice"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:ice_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.intelligent", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:intelligent"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:arcane_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.lightning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:lightning"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:lightning_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.nature", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:nature"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:nature_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.spell_resist", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:spell_resist"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:protection_rune>, <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.summoning", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "irons_spellbooks:summoning"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:irons_spellbooks:conjurers_talisman>.anyDamage(), <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);
craftingTable.addShaped("irons_spellbooks.epic_ink_to_epic_material.breach", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:core/breach"}), [[<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>], [<item:apotheosis:epic_material>, <item:cataclysm:void_core>.anyDamage(), <item:apotheosis:epic_material>], [<item:irons_spellbooks:epic_ink>, <item:cataclysm:ignitium_ingot>, <item:irons_spellbooks:epic_ink>]]);











