import crafttweaker.api.ingredient.IIngredient;

//诅咒
<item:goety:cursed_knight_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.cursed_knight_helmet.3", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:goety:cursed_paladin_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.cursed_paladin_chestplate.3", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:goety:cursed_knight_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.cursed_knight_leggings.3", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:goety:cursed_paladin_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.cursed_paladin_boots.3", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:goety:cursed_knight_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:moonstone:all_attack> , "attribute.cursed_knight_helmet", -0.2, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:goety:cursed_paladin_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:moonstone:all_attack> , "attribute.cursed_paladin_chestplate", -0.30, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:goety:cursed_knight_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:moonstone:all_attack> , "attribute.cursed_knight_leggings", -0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:goety:cursed_paladin_boots>.anyDamage().addGlobalAttributeModifier(<attribute:moonstone:all_attack> , "attribute.cursed_paladin_boots", -0.2, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:goety:cursed_knight_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.cursed_knight_helmet.1", 8, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:goety:cursed_paladin_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.cursed_paladin_chestplate.1", 13, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:goety:cursed_knight_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.cursed_knight_leggings.1", 5, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:goety:cursed_paladin_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.cursed_paladin_boots.1", 7, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
<item:goety:cursed_knight_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor_toughness> , "attribute.cursed_knight_helmet.2", 4.5, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:goety:cursed_paladin_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor_toughness> , "attribute.cursed_paladin_chestplate.2", 4, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:goety:cursed_knight_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor_toughness> , "attribute.cursed_knight_leggings.2", 4.5, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:goety:cursed_paladin_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor_toughness> , "attribute.cursed_paladin_boots.2", 4, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

//瓦琍斯
<item:distant_worlds:vairis_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.vairis_helmet.1", 50.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:vairis_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.vairis_chestplate.1", 50.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:vairis_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.vairis_leggings.1", 50.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:vairis_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.vairis_boots.1", 50.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

//锁链
<item:minecraft:chainmail_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.chainmail_helmet.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:minecraft:chainmail_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.chainmail_chestplate.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:minecraft:chainmail_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.chainmail_leggings.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:minecraft:chainmail_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.chainmail_boots.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:minecraft:chainmail_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.chainmail_helmet.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:minecraft:chainmail_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.chainmail_chestplate.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:minecraft:chainmail_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.chainmail_leggings.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:minecraft:chainmail_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.chainmail_boots.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:minecraft:chainmail_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.chainmail_helmet.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:minecraft:chainmail_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.chainmail_chestplate.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:minecraft:chainmail_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.chainmail_leggings.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:minecraft:chainmail_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.chainmail_boots.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:minecraft:chainmail_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.chainmail_helmet.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:minecraft:chainmail_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.chainmail_chestplate.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:minecraft:chainmail_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.chainmail_leggings.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:minecraft:chainmail_boots>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.chainmail_boots.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//神秘金
<item:wizards_reborn:arcane_gold_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.arcane_gold_helmet.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:wizards_reborn:arcane_gold_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.arcane_gold_chestplate.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:wizards_reborn:arcane_gold_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.arcane_gold_leggings.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:wizards_reborn:arcane_gold_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.arcane_gold_boots.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:wizards_reborn:arcane_gold_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.arcane_gold_helmet.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:wizards_reborn:arcane_gold_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.arcane_gold_chestplate.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:wizards_reborn:arcane_gold_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.arcane_gold_leggings.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:wizards_reborn:arcane_gold_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.arcane_gold_boots.2", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:wizards_reborn:arcane_gold_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.arcane_gold_helmet.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:wizards_reborn:arcane_gold_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.arcane_gold_chestplate.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:wizards_reborn:arcane_gold_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.arcane_gold_leggings.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:wizards_reborn:arcane_gold_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.arcane_gold_boots.3", 1.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:wizards_reborn:arcane_gold_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.arcane_gold_helmet.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:wizards_reborn:arcane_gold_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.arcane_gold_chestplate.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:wizards_reborn:arcane_gold_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.arcane_gold_leggings.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:wizards_reborn:arcane_gold_boots>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.arcane_gold_boots.4", 0.05, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//重力
<item:aether:gravitite_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.gravitite_helmet.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:gravitite_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.gravitite_chestplate.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:gravitite_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.gravitite_leggings.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:gravitite_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.gravitite_boots.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:aether:gravitite_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.gravitite_helmet.2", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:gravitite_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.gravitite_chestplate.2", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:gravitite_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.gravitite_leggings.2", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:gravitite_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.gravitite_boots.2", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//凤凰
<item:aether:phoenix_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.phoenix_helmet.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:phoenix_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.phoenix_chestplate.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:phoenix_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.phoenix_leggings.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:phoenix_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.phoenix_boots.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:aether:phoenix_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.phoenix_helmet.2", 3.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:phoenix_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.phoenix_chestplate.2", 3.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:phoenix_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.phoenix_leggings.2", 3.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:phoenix_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.phoenix_boots.2", 3.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//女武神
<item:ancient_aether:valkyrum_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.valkyrum_helmet.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:ancient_aether:valkyrum_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.valkyrum_chestplate.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:ancient_aether:valkyrum_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.valkyrum_leggings.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:ancient_aether:valkyrum_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.valkyrum_boots.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:ancient_aether:valkyrum_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.valkyrum_helmet.2", 6.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:ancient_aether:valkyrum_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.valkyrum_chestplate.2", 6.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:ancient_aether:valkyrum_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.valkyrum_leggings.2", 6.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:ancient_aether:valkyrum_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.valkyrum_boots.2", 6.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:ancient_aether:valkyrum_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:critical_hit> , "attribute.valkyrum_helmet.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:ancient_aether:valkyrum_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:critical_hit> , "attribute.valkyrum_chestplate.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:ancient_aether:valkyrum_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:critical_hit> , "attribute.valkyrum_leggings.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:ancient_aether:valkyrum_boots>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:critical_hit> , "attribute.valkyrum_boots.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//穹玉
<item:deep_aether:skyjade_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.skyjade_helmet.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:deep_aether:skyjade_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.skyjade_chestplate.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:deep_aether:skyjade_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.skyjade_leggings.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:deep_aether:skyjade_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.skyjade_boots.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:deep_aether:skyjade_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.skyjade_helmet.2", 0.2, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:deep_aether:skyjade_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.skyjade_chestplate.2", 0.2, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:deep_aether:skyjade_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.skyjade_leggings.2", 0.2, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:deep_aether:skyjade_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.skyjade_boots.2", 0.2, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
<item:deep_aether:skyjade_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.skyjade_helmet.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:deep_aether:skyjade_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.skyjade_chestplate.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:deep_aether:skyjade_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.skyjade_leggings.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:deep_aether:skyjade_boots>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.skyjade_boots.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:deep_aether:skyjade_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.skyjade_helmet.4", 250, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:deep_aether:skyjade_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.skyjade_chestplate.4", 250, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:deep_aether:skyjade_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.skyjade_leggings.4", 250, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:deep_aether:skyjade_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.skyjade_boots.4", 250, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

//翡翠
<item:call_of_yucutan:jades_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.jades_helmet.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:call_of_yucutan:jades_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.jades_chestplate.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:call_of_yucutan:jades_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.jades_leggings.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:call_of_yucutan:jades_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.jades_boots.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:call_of_yucutan:jades_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.jades_helmet.2", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:call_of_yucutan:jades_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.jades_chestplate.2", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:call_of_yucutan:jades_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.jades_leggings.2", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:call_of_yucutan:jades_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.jades_boots.2", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
<item:call_of_yucutan:jades_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.jades_helmet.3", 0.55, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:call_of_yucutan:jades_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.jades_chestplate.3", 0.55, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:call_of_yucutan:jades_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.jades_leggings.3", 0.55, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:call_of_yucutan:jades_boots>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.jades_boots.3", 0.55, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:call_of_yucutan:jades_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.jades_helmet.4", 750, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:call_of_yucutan:jades_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.jades_chestplate.4", 750, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:call_of_yucutan:jades_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.jades_leggings.4", 750, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:call_of_yucutan:jades_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.jades_boots.4", 750, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

//菲隆
<item:distant_worlds:firon_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.firon_helmet.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:firon_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.firon_chestplate.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:firon_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.firon_leggings.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:firon_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.firon_boots.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:distant_worlds:firon_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.firon_helmet.2", 2.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:firon_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.firon_chestplate.2", 2.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:firon_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.firon_leggings.2", 2.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:firon_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.firon_boots.2", 2.25, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);
<item:distant_worlds:firon_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.firon_helmet.3", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:firon_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.firon_chestplate.3", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:firon_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.firon_leggings.3", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:firon_boots>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.firon_boots.3", 1.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:distant_worlds:firon_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.firon_helmet.4", 3000, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:firon_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.firon_chestplate.4", 3000, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:firon_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.firon_leggings.4", 3000, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:firon_boots>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:max_mana> , "attribute.firon_boots.4", 3000, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:feet>]);

//紫晶
<item:aether:zanite_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.zanite_helmet.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:zanite_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.zanite_chestplate.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:zanite_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.zanite_leggings.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:zanite_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.zanite_boots.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:aether:zanite_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_helmet.2", 7.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:zanite_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_chestplate.2", 7.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:zanite_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_leggings.2", 7.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:zanite_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_boots.2", 7.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//海皇
<item:aether:neptune_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.neptune_helmet.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:neptune_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.neptune_chestplate.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:neptune_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.neptune_leggings.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:neptune_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.neptune_boots.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:aether:neptune_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.neptune_helmet.2", 65, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:aether:neptune_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.neptune_chestplate.2", 65, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:aether:neptune_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.neptune_leggings.2", 65, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:aether:neptune_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.neptune_boots.2", 65, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//海琍斯特
<item:distant_worlds:helyst_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.helyst_helmet.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:helyst_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.helyst_chestplate.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:helyst_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.helyst_leggings.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:helyst_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.helyst_boots.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:distant_worlds:helyst_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.helyst_helmet.2", 252, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:distant_worlds:helyst_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.helyst_chestplate.2", 252, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:distant_worlds:helyst_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.helyst_leggings.2", 252, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:distant_worlds:helyst_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.helyst_boots.2", 252, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//紫晶盔甲
<item:majruszsdifficulty:enderium_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.enderium_helmet.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:majruszsdifficulty:enderium_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.enderium_chestplate.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:majruszsdifficulty:enderium_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.enderium_leggings.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:majruszsdifficulty:enderium_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.enderium_boots.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:majruszsdifficulty:enderium_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.enderium_helmet.2", 3500, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:majruszsdifficulty:enderium_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.enderium_chestplate.2", 3500, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:majruszsdifficulty:enderium_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.enderium_leggings.2", 3500, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:majruszsdifficulty:enderium_boots>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.enderium_boots.2", 3500, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//灾厄皇家
<item:illager_additions:royal_guard_spearman_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.royal_guard_spearman_helmet.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:illager_additions:royal_guard_spearman_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.royal_guard_spearman_chestplate.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:illager_additions:royal_guard_spearman_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.royal_guard_spearman_leggings.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:illager_additions:royal_guard_spearman_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.royal_guard_spearman_boots.1", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:illager_additions:royal_guard_spearman_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.royal_guard_spearman_helmet.2", 0.1, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:illager_additions:royal_guard_spearman_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.royal_guard_spearman_chestplate.2", 0.1, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:illager_additions:royal_guard_spearman_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.royal_guard_spearman_leggings.2", 0.1, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:illager_additions:royal_guard_spearman_boots>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.royal_guard_spearman_boots.2", 0.1, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//幽匿
<item:callfromthedepth_:depth_armor_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.depth_armor_helmet.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:callfromthedepth_:depth_armor_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.depth_armor_chestplate.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:callfromthedepth_:depth_armor_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.depth_armor_leggings.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:callfromthedepth_:depth_armor_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.depth_armor_boots.1", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:callfromthedepth_:depth_armor_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.depth_armor_helmet.2", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:callfromthedepth_:depth_armor_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.depth_armor_chestplate.2", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:callfromthedepth_:depth_armor_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.depth_armor_leggings.2", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:callfromthedepth_:depth_armor_boots>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.depth_armor_boots.2", 0.75, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);

//空域
<item:locusazzurro_icaruswings:synapse_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.synapse_helmet.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:locusazzurro_icaruswings:synapse_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.synapse_chestplate.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:locusazzurro_icaruswings:synapse_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.synapse_leggings.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:locusazzurro_icaruswings:synapse_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.synapse_boots.1", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);
<item:locusazzurro_icaruswings:synapse_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.synapse_helmet.2", 1.85, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:head>]);
<item:locusazzurro_icaruswings:synapse_chestplate>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.synapse_chestplate.2", 1.85, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:chest>]);
<item:locusazzurro_icaruswings:synapse_leggings>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.synapse_leggings.2", 1.85, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:legs>]);
<item:locusazzurro_icaruswings:synapse_boots>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.synapse_boots.2", 1.85, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:feet>]);


//盾牌
<item:deep_aether:skyjade_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.max_health> , "attribute.skyjade_shield.2", 100.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:skyjade_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.skyjade_shield.3", 50.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:skyjade_shield>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.skyjade_shield.4", 3.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:skyjade_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.skyjade_shield.5", 80.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:skyjade_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.skyjade_shield.6", 4.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);

<item:shieldexp:wooden_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.wooden_shield.2", 20.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:wooden_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.wooden_shield.3", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:iron_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.iron_shield.2", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:iron_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.iron_shield.3", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:golden_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.golden_shield.2", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:golden_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.golden_shield.3", 3.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:diamond_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.diamond_shield.2", 60.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:diamond_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.diamond_shield.3", 3.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:netherite_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.knockback_resistance> , "attribute.netherite_shield", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);

//近战盾牌
<item:shieldexp:griefer_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.griefer_shield.3", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:griefer_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.griefer_shield.2", 520.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:hmag:fortress_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.fortress_shield.2", 950.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:hmag:fortress_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.fortress_shield.3", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:hmag:ancient_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.ancient_shield.2", 4650.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:hmag:ancient_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.ancient_shield.3", 60.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:paragon_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.paragon_shield.2", 13725.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:shieldexp:paragon_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.paragon_shield.3", 80.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);

//枪械盾牌
<item:deep_aether:stratus_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.shield_of_emile.3", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:stratus_shield>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.shield_of_emile.2", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:deep_aether:stratus_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.shield_of_emile.4", 6.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:enigmaticlegacy:infernal_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.infernal_shield.3", 80.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:enigmaticlegacy:infernal_shield>.anyDamage().addGlobalAttributeModifier(<attribute:gunsmithlib:bullet_damage> , "attribute.infernal_shield.2", 6.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:enigmaticlegacy:infernal_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.movement_speed> , "attribute.infernal_shield.4", 10.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);

//弓箭 盾牌
<item:lost_aether_content:zanite_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.zanite_shield.3", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:lost_aether_content:zanite_shield>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_shield.2", 60.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:lost_aether_content:gravitite_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.zanite_shield.3", 60.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:lost_aether_content:gravitite_shield>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.zanite_shield.2", 520.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:black_steel_targe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.black_steel_targe.3", 80.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:black_steel_targe>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.black_steel_targe.2", 7150.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:bulwark_of_the_flame>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.bulwark_of_the_flame.3", 80.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:bulwark_of_the_flame>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:arrow_damage> , "attribute.bulwark_of_the_flame.2", 21500.0, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);

//不可破坏装备
craftingTable.addShapeless("minecraft.diamond_sword.unbreakable", <item:minecraft:diamond_sword>.withTag({Unbreakable:1}), [<item:minecraft:diamond_sword>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("minecraft.leather_helmet.unbreakable", <item:minecraft:leather_helmet>.withTag({Unbreakable:1}), [<item:minecraft:leather_helmet>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("minecraft.leather_chestplate.unbreakable", <item:minecraft:leather_chestplate>.withTag({Unbreakable:1}), [<item:minecraft:leather_chestplate>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("minecraft.leather_leggings.unbreakable", <item:minecraft:leather_leggings>.withTag({Unbreakable:1}), [<item:minecraft:leather_leggings>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("minecraft.leather_boots.unbreakable", <item:minecraft:leather_boots>.withTag({Unbreakable:1}), [<item:minecraft:leather_boots>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("shieldexp.wooden_shield.unbreakable", <item:shieldexp:wooden_shield>.withTag({Unbreakable:1}), [<item:shieldexp:wooden_shield>.anyDamage(), <item:celestial_artifacts:purified_powder>, <item:yuusha:bad_soul_gem>.reuse()]);

//法师杖加伤
<item:malum:mnemonic_hex_staff>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.mnemonic_hex_staff.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:mainhand>]);
<item:malum:mnemonic_hex_staff>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.mnemonic_hex_staff.2", 0.15, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:mainhand>]);
<item:malum:mnemonic_hex_staff>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:penetration> , "attribute.mnemonic_hex_staff.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_TOTAL, [<constant:minecraft:equipmentslot:mainhand>]);

//法师盾牌
<item:cataclysm:azure_sea_shield>.anyDamage().addGlobalAttributeModifier(<attribute:lodestone:magic_proficiency> , "attribute.azure_sea_shield.1", 0.5, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:azure_sea_shield>.anyDamage().addGlobalAttributeModifier(<attribute:irons_spellbooks:spell_power> , "attribute.azure_sea_shield.2", 0.15, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_BASE, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:azure_sea_shield>.anyDamage().addGlobalAttributeModifier(<attribute:obscure_api:penetration> , "attribute.azure_sea_shield.3", 0.25, crafttweaker.api.entity.attribute.AttributeOperation.MULTIPLY_TOTAL, [<constant:minecraft:equipmentslot:offhand>]);
<item:cataclysm:azure_sea_shield>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor> , "attribute.azure_sea_shield.4", 40.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:offhand>]);

//近战武器加伤
<item:lost_aether_content:phoenix_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.phoenix_sword", 135.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:mokels_boss_mantyd:mantyd_scythe>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.mantyd_scythe", 254.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:cataclysm:coral_spear>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.coral_spear.2", 378.5, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:born_in_chaos_v1:frostbitten_blade>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.frostbitten_blade", 519.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:call_of_yucutan:macuahuitl>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.macuahuitl.1", 915.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:cataclysm:void_forge>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.void_forge.1", 1135.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:callfromthedepth_:immemorialsword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.immemorialsword", 956.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:irons_spellbooks:spellbreaker>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.spellbreaker", 1215.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:callfromthedepth_:soul_blade>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.soul_blade", 1556.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:forbidden_arcanus:draco_arcanus_sword>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.draco_arcanus_sword", 3523.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:depthcrawler:redtenebris>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.redtenebris", 7520.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:malum:tyrving>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.attack_damage> , "attribute.tyrving.1", 63495.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:malum:tyrving>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:crit_chance> , "attribute.tyrving.2", 2.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);
<item:malum:tyrving>.anyDamage().addGlobalAttributeModifier(<attribute:attributeslib:crit_damage> , "attribute.tyrving.3", 1.0, crafttweaker.api.entity.attribute.AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:mainhand>]);

//猎人腰带升级
craftingTable.addShaped("relics.hunter_belt.15", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 15}}, leveling: {level: 30}, display: {Name: "{\"text\":\"猎人腰带「超限」1阶\"}"}}), [[<item:aquaculture:neptunium_ingot>, <item:mowziesmobs:wrought_axe>.anyDamage(), <item:aquaculture:neptunium_ingot>], [<item:irons_spellbooks:uncommon_ink>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:irons_spellbooks:uncommon_ink>], [<item:aquaculture:neptunium_ingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:aquaculture:neptunium_ingot>]]);

craftingTable.addShaped("relics.hunter_belt.25", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 25}}, leveling: {level: 50}, display: {Name: "{\"text\":\"猎人腰带「超限」2阶\"}"}}), [[<item:call_of_drowner:seagold_ingot>, <item:aquamirae:sweet_lance>.anyDamage(), <item:call_of_drowner:seagold_ingot>], [<item:irons_spellbooks:rare_ink>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:irons_spellbooks:rare_ink>], [<item:call_of_drowner:seagold_ingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:call_of_drowner:seagold_ingot>]]);

craftingTable.addShaped("relics.hunter_belt.35", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 35}}, leveling: {level: 70}, display: {Name: "{\"text\":\"猎人腰带「超限」3阶\"}"}}), [[<item:callfromthedepth_:soulingot>, <item:callfromthedepth_:soulbell>, <item:callfromthedepth_:soulingot>], [<item:goety:shadow_essence>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:goety:shadow_essence>], [<item:callfromthedepth_:soulingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:callfromthedepth_:soulingot>]]);

craftingTable.addShaped("relics.hunter_belt.59", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 59}}, leveling: {level: 118}, display: {Name: "{\"text\":\"猎人腰带「超限」4阶\"}"}}), [[<item:cataclysm:ignitium_ingot>, <item:cataclysm:monstrous_horn>, <item:cataclysm:ignitium_ingot>], [<item:yuusha:burn_core>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:yuusha:burn_core>], [<item:cataclysm:ignitium_ingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:cataclysm:ignitium_ingot>]]);

craftingTable.addShaped("relics.hunter_belt.85", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 85}}, leveling: {level: 170}, display: {Name: "{\"text\":\"猎人腰带「超限」5阶\"}"}}), [[<item:yuusha:twist_ingot>, <item:faded_conquest_2:eye_of_the_storm>, <item:yuusha:twist_ingot>], [<item:arcalis_bosses:cursed_cloth_shard>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:arcalis_bosses:cursed_cloth_shard>], [<item:yuusha:twist_ingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:yuusha:twist_ingot>]]);

craftingTable.addShaped("relics.hunter_belt.160", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 160}}, leveling: {level: 320}, display: {Name: "{\"text\":\"猎人腰带「超限」6阶\"}"}}), [[<item:depthcrawler:corruptingot>, <item:apotheosis:ancient_material>, <item:depthcrawler:corruptingot>], [<item:depthcrawler:reinforcedeye>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:depthcrawler:reinforcedeye>], [<item:depthcrawler:corruptingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:depthcrawler:corruptingot>]]);

craftingTable.addShaped("relics.hunter_belt.375", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 375}}, leveling: {level: 750}, display: {Name: "{\"text\":\"猎人腰带「超限」7阶\"}"}}), [[<item:yuusha:calamity_ingot>, <item:enigmaticaddons:thunder_scroll>.anyDamage(), <item:yuusha:calamity_ingot>], [<item:cataclysm:cursed_eye>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:cataclysm:cursed_eye>], [<item:yuusha:calamity_ingot>, <item:yuusha:bad_soul_gem>.reuse(), <item:yuusha:calamity_ingot>]]);

craftingTable.addShaped("relics.hunter_belt.625", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 625}}, leveling: {level: 1350}, display: {Name: "{\"text\":\"猎人腰带「超限」8阶\"}"}}), [[<item:yuusha:orichalcum>, <item:celestial_artifacts:war_dead_badge>.anyDamage(), <item:yuusha:orichalcum>], [<item:stalwart_dungeons:void_crystal>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:stalwart_dungeons:void_crystal>], [<item:yuusha:orichalcum>, <item:yuusha:bad_soul_gem>.reuse(), <item:yuusha:orichalcum>]]);

craftingTable.addShaped("relics.hunter_belt.19990", <item:relics:hunter_belt>.withTag({abilities: {slots: {stats: {charm: 1.0}, points: 0}, training: {stats: {damage: 2.5}, points: 19990}}, leveling: {level: 39980}, display: {Name: "{\"text\":\"猎人腰带「超限」9阶\"}"}}), [[<item:yuusha:orichalcum>, <item:moonstone:plagues>.anyDamage(), <item:yuusha:orichalcum>], [<item:yuusha:emper_core>, <item:wizards_reborn:leather_belt>.anyDamage(), <item:yuusha:emper_core>], [<item:yuusha:orichalcum>, <item:yuusha:bad_soul_gem>.reuse(), <item:yuusha:orichalcum>]]);

//分解材料
craftingTable.addShapeless("graveyard.vial_of_blood.bad_soul_gem", <item:graveyard:vial_of_blood>.withTag({Blood: 0.8000001}), [<item:born_in_chaos_v1:elixir_of_vampirism>, <item:bhc:soul_heart_crystal>, <item:graveyard:bone_dagger>.reuse(), <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("celestial_core.pure_nether_star.bad_soul_gem", <item:celestial_core:pure_nether_star>, [<item:minecraft:nether_star>, <item:hmag:purification_cloth>, <item:hmag:purification_cloth>, <item:hmag:purification_cloth>, <item:hmag:purification_cloth>, <item:yuusha:bad_soul_gem>.reuse()]);

//红色渊剑
craftingTable.remove(<item:depthcrawler:redtenebris>);
craftingTable.addShaped("depthcrawler.redtenebris", <item:depthcrawler:redtenebris>, [[<item:minecraft:air>, <item:cataclysm:ignitium_ingot>, <item:yuusha:chaos_star>], [<item:locusazzurro_icaruswings:synapse_alloy_ingot>, <item:bosses_of_mass_destruction:blazing_eye>, <item:cataclysm:ignitium_ingot>], [<item:enigmaticlegacy:ender_rod>, <item:locusazzurro_icaruswings:synapse_alloy_ingot>, <item:minecraft:air>]]);

//守卫者眼球
craftingTable.addShapeless("celestial_artifacts.guardian_eye.bad_soul_gem", <item:celestial_artifacts:guardian_eye>, [<item:endrem:guardian_eye>.anyDamage(), <item:yuusha:bad_soul_gem>.reuse()]);

//生命与奇迹之果
craftingTable.addShapeless("yuusha.life_fruit.bad_soul_gem", <item:yuusha:life_fruit>, [<item:immortalers_delight:enchanted_golden_himekaido>, <item:immortalers_delight:enchanted_golden_himekaido>, <item:immortalers_delight:enchanted_golden_himekaido>, <item:immortalers_delight:enchanted_golden_himekaido>, <item:yuusha:bad_soul_gem>.reuse()]);

//下界狱星
craftingTable.addShaped("yuusha.chaos_star", <item:yuusha:chaos_star>, [[<item:yuusha:moon_core>, <item:forbidden_arcanus:dark_nether_star>, <item:yuusha:moon_core>], [<item:forbidden_arcanus:dark_nether_star>, <item:cataclysm:monstrous_eye>, <item:forbidden_arcanus:dark_nether_star>], [<item:yuusha:moon_core>, <item:forbidden_arcanus:dark_nether_star>, <item:yuusha:moon_core>]]);

//诡异蝇蛆
craftingTable.addShaped("born_in_chaos_v1.excessflyswattericon.yuusha.1", <item:yuusha:chaos_fly>*4, [[<item:yuusha:moon_core>, <item:avaritia:ultimate_stew>, <item:yuusha:moon_core>], [<item:avaritia:ultimate_stew>, <item:bosses_of_mass_destruction:blazing_eye>, <item:avaritia:ultimate_stew>], [<item:yuusha:moon_core>, <item:avaritia:ultimate_stew>, <item:yuusha:moon_core>]]);
craftingTable.addShaped("born_in_chaos_v1.excessflyswattericon.yuusha.2", <item:yuusha:chaos_fly>*4, [[<item:yuusha:moon_core>, <item:avaritia:cosmic_meatballs>, <item:yuusha:moon_core>], [<item:avaritia:cosmic_meatballs>, <item:bosses_of_mass_destruction:blazing_eye>, <item:avaritia:cosmic_meatballs>], [<item:yuusha:moon_core>, <item:avaritia:cosmic_meatballs>, <item:yuusha:moon_core>]]);

//宝石
craftingTable.addShaped("apotheosis.royalty", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:overworld/royalty"}), [[<item:apotheosis:uncommon_material>, <item:enigmaticlegacy:etherium_ingot>, <item:apotheosis:uncommon_material>], [<item:enigmaticlegacy:etherium_ingot>, <item:yuusha:moon_core>, <item:enigmaticlegacy:etherium_ingot>], [<item:apotheosis:uncommon_material>, <item:enigmaticlegacy:etherium_ingot>, <item:apotheosis:uncommon_material>]]);
craftingTable.addShaped("apotheosis.earth", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:uncommon"}, gem: "apotheosis:overworld/earth"}), [[<item:apotheosis:uncommon_material>, <item:cataclysm:enderite_ingot>, <item:apotheosis:uncommon_material>], [<item:cataclysm:enderite_ingot>, <item:yuusha:moon_core>, <item:cataclysm:enderite_ingot>], [<item:apotheosis:uncommon_material>, <item:cataclysm:enderite_ingot>, <item:apotheosis:uncommon_material>]]);

craftingTable.addShaped("apotheosis.inferno", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:the_nether/inferno"}), [[<item:apotheosis:rare_material>, <item:luminous_halloween:spooky_apple>, <item:apotheosis:rare_material>], [<item:luminous_halloween:spooky_apple>, <item:yuusha:moon_core>, <item:luminous_halloween:spooky_apple>], [<item:apotheosis:rare_material>, <item:luminous_halloween:spooky_apple>, <item:apotheosis:rare_material>]]);
craftingTable.addShaped("apotheosis.blood_lord", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:rare"}, gem: "apotheosis:the_nether/blood_lord"}), [[<item:apotheosis:rare_material>, <item:luminous_halloween:halloween_ingot>, <item:apotheosis:rare_material>], [<item:luminous_halloween:halloween_ingot>, <item:yuusha:moon_core>, <item:luminous_halloween:halloween_ingot>], [<item:apotheosis:rare_material>, <item:luminous_halloween:halloween_ingot>, <item:apotheosis:rare_material>]]);

craftingTable.addShaped("apotheosis.mageslayer", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_end/mageslayer"}), [[<item:apotheosis:epic_material>, <item:cataclysm:witherite_ingot>, <item:apotheosis:epic_material>], [<item:cataclysm:witherite_ingot>, <item:yuusha:moon_core>, <item:cataclysm:witherite_ingot>], [<item:apotheosis:epic_material>, <item:cataclysm:witherite_ingot>, <item:apotheosis:epic_material>]]);
craftingTable.addShaped("apotheosis.endersurge", <item:apotheosis:gem>.withTag({affix_data: {rarity: "apotheosis:epic"}, gem: "apotheosis:the_end/endersurge"}), [[<item:apotheosis:epic_material>, <item:locusazzurro_icaruswings:sapphire_gem>, <item:apotheosis:epic_material>], [<item:locusazzurro_icaruswings:sapphire_gem>, <item:yuusha:moon_core>, <item:locusazzurro_icaruswings:sapphire_gem>], [<item:apotheosis:epic_material>, <item:locusazzurro_icaruswings:sapphire_gem>, <item:apotheosis:epic_material>]]);

//附魔
craftingTable.addShaped("minecraft.enchanted_book.protection.10.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 10 as short, id: "minecraft:protection" as string}]}), [[<item:constructionwand:core_angel>, <item:yuusha:bad_soul_gem>.reuse()]]);
craftingTable.addShaped("minecraft.enchanted_book.protection.20.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 20 as short, id: "minecraft:protection" as string}]}), [[<item:forbidden_arcanus:dragon_scale>, <item:yuusha:bad_soul_gem>.reuse()]]);
craftingTable.addShapeless("elementalcombat.enchanted_book.magic_protection.2.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 10 as short, id: "elementalcombat:magic_protection" as string}]}), [<item:constructionwand:core_destruction>, <item:yuusha:bad_soul_gem>.reuse()]);

craftingTable.addShaped("majruszsenchantments.enchanted_book.magic_protection.10.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 10 as short, id: "majruszsenchantments:magic_protection" as string}]}), [[<item:yuusha:bad_soul_gem>.reuse(), <item:constructionwand:core_angel>]]);
craftingTable.addShaped("majruszsenchantments.enchanted_book.magic_protection.20.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 20 as short, id: "majruszsenchantments:magic_protection" as string}]}), [[<item:yuusha:bad_soul_gem>.reuse(), <item:forbidden_arcanus:dragon_scale>]]);

craftingTable.addShapeless("majruszsenchantments.enchanted_book.destruction_crack.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1, id: "celestial_enchantments:destruction_crack"}]}), [<item:meetyourfight:phantoplasm>, <item:yuusha:bad_soul_gem>.reuse()]);
craftingTable.addShapeless("majruszsenchantments.enchanted_book.magic_blade.bad_soul_gem", <item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1, id: "celestial_enchantments:magic_blade"}]}), [<item:yuusha:chaos_ingot>, <item:yuusha:bad_soul_gem>.reuse()]);











